services:
  db:
    image: postgres:16-alpine
    container_name: cafe_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # Pasamos estas variables para que el script 05_roles.sh pueda usarlas
      DB_VIEWER_USER: ${DB_VIEWER_USER}
      DB_VIEWER_PASSWORD: ${DB_VIEWER_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/03_seed.sql
      - ./db/views.sql:/docker-entrypoint-initdb.d/04_views.sql
      - ./db/05_roles.sh:/docker-entrypoint-initdb.d/05_roles.sh
    ports:
      - "${POSTGRES_PORT}:5432"

  app:
    build: .
    container_name: cafe_app
    restart: always
    environment:
      # En Docker, el host debe ser el nombre del servicio ('db'), no 'localhost'
      DATABASE_URL: postgres://${DB_VIEWER_USER}:${DB_VIEWER_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      NODE_ENV: ${NODE_ENV}
      ROLE_ADMIN: ${ROLE_ADMIN}
      ROLE_USER: ${ROLE_USER}
      DISABLE_SSL: "true"
    ports:
      - "${PORT}:3000"
    depends_on:
      - db

volumes:
  db_data:
